version: '2'
services:
    registrator:
        hostname: registrator
        image: gliderlabs/registrator
        restart: always
        depends_on:
            - consul
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        command: '-internal consul://consul:8500'

    consul:
        hostname: consul
        image: consul
        restart: always
        ports:
            - '8500:8500'
            - '8600:8600/udp'
        command: ["agent", "-dev", "-domain", "docker", "-client", "0.0.0.0"]

